name: publish package
on:
  release:
    types: [created]
jobs:
  publish-brew:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.4.x"
      - run: yarn

      - name: Pack tarball
        run: npx oclif pack tarballs -t darwin-x64 --no-xz

      - name: Query tarball
        id: tarball
        run: echo "filename=$(ls ./dist/*darwin-x64.tar.gz | head -1 | xargs -n 1 basename)" >> $GITHUB_OUTPUT

      # - run: mv dist/*-darwin-x64.tar.gz dist/groot-${GITHUB_REF_NAME}-darwin-x64.tar.gz

      - name: Upload tarball
        run: gh release upload ${GITHUB_REF_NAME} ./dist/${{ steps.tarball.outputs.filename }}

      # - name: Check tarball filename
      #   run: echo ${{ steps.tarball.outputs.filename }}

      # echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # - name: Set SHA
      #   id: shasum
      #   run: |
      #     echo ::set-output name=sha::"$(shasum -a 256 dist/*-darwin-x64.tar.gz | awk '{printf $1}')"

      # - uses: mislav/bump-homebrew-formula-action@v2
      #   if: "!contains(github.ref, '-')" # skip prereleases
      #   with:
      #     formula-name: groot
      #     homebrew-tap: knocklabs/homebrew-tap
      #     download-url: https://example.com/foo/${{ steps.extract-version.outputs.tag-name }}.tar.gz
      #     commit-message: |
      #       {{formulaName}} {{version}}
      #
      #       Created by https://github.com/mislav/bump-homebrew-formula-action
      #   env:
      #     COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # publish-npm:
