name: publish package
on:
  release:
    types: [created]
jobs:
  publish-brew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.4.x"
      - run: yarn

      - name: Pack tarball
        run: npx oclif pack tarballs -t darwin-x64 --no-xz

      - name: Set tarball vars
        id: tarball
        run: |
          FILENAME=$(ls ./dist/*darwin-x64.tar.gz | head -1 | xargs -n 1 basename)
          echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
          echo "download_url=https://github.com/knocklabs/knock-groot/releases/download/${GITHUB_REF_NAME}/${FILENAME}" >> $GITHUB_OUTPUT

      - run: gh release delete-asset ${GITHUB_REF_NAME} ${{ steps.tarball.outputs.filename }} --yes

      - name: Upload tarball to the release
        run: gh release upload ${GITHUB_REF_NAME} ./dist/${{ steps.tarball.outputs.filename }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update brew tap
        uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          homebrew-tap: knocklabs/homebrew-tap
          formula-name: groot
          download-url: ${{ steps.tarball.outputs.download_url }}
          create-pullrequest: true
          commit-message: |
            release: {{formulaName}} {{version}}

            This PR is opened and managed automatically by Github Actions.

            formula: {{formulaName}}
            version: {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

  # publish-npm:
